baseURL = 'https://0vertex.github.io/0vertex/'
languageCode = 'en-us'
title = '0vertex'

markup.highlight.noClasses=false

[related]
threshold = 80
includeNewer = true
toLower = false
[[related.indices]]
name  = "tags"
weight = 100
[[related.indices]]
name  = "categories"
weight = 140